#!/usr/bin/env python
import nupay

from_ = 'tokens@muc.ccc.de'
to = 'schneider@xtort.eu'
mail_server = "mail.xtort.eu"
mail_server_port = 0 #587

if __name__ == '__main__':
    mail_collector = nupay.MailCollector(from_, to, mail_server, mail_server_port)
    collectors = [mail_collector]
    forwarder = nupay.MQTTTokenForwarder('localhost', '/collected/#', 'mail-forwarder', collectors, timeout = 10)
    forwarder.join()
    
