#!/usr/bin/env python
import nupay
import ConfigParser
import signal

def read_config(config_location):
    config = ConfigParser.RawConfigParser()
    config.read(config_location)
    return config

if __name__ == '__main__':
    config = read_config('/etc/upay/mqtt-git-forwarder.cfg')

    git_collector = nupay.GITCollector(config.get('GIT', 'URL'))
    collectors = [git_collector]
    mqtt_server = config.get('MQTT', 'server')
    mqtt_topic = config.get('MQTT', 'topic')
    mqtt_client_id = config.get('MQTT', 'client_id')
    forwarder = nupay.MQTTTokenForwarder(mqtt_server, mqtt_topic, mqtt_client_id, collectors)
    signal.signal(signal.SIGINT, lambda signal, frame: forwarder.stop())
    signal.pause()
    forwarder.join()

